#!/usr/bin/env bash
set -euo pipefail

function write_error {
	echo "error(1): $1" 2>&1
	exit 1
}

builtin type -P dotnet &>/dev/null || write_error "Could not find 'dotnet'; please install the .NET SDK from https://dot.net/"

dotnet tool restore
dotnet restore
dotnet build --no-restore --configuration Release
dotnet test --no-build --configuration Release --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura.xml --coverage-settings .runsettings
dotnet reportgenerator -reports:**/TestResults/**/coverage.cobertura.xml -targetdir:CoverageReport -reporttypes:"TextSummary" -verbosity:off
echo ""
echo -e "\e[32mCode coverage report:\e[0m"
echo ""
cat CoverageReport/Summary.txt
