//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyphen.Sdk.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HyphenSdkResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HyphenSdkResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hyphen.Sdk.Resources.HyphenSdkResources", typeof(HyphenSdkResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key is required. Please provide it via options or set the HYPHEN_API_KEY environment variable..
        /// </summary>
        internal static string ApiKey_Required {
            get {
                return ResourceManager.GetString("ApiKey_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided API key is a public API key. Please provide a valid non public API key for authentication..
        /// </summary>
        internal static string ApiKey_ShouldNotBePublic {
            get {
                return ResourceManager.GetString("ApiKey_ShouldNotBePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While parsing &quot;{0}&quot;, line &quot;{1}&quot; was not valid..
        /// </summary>
        internal static string Env_InvalidLineFmt {
            get {
                return ResourceManager.GetString("Env_InvalidLineFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment variable &quot;{0}&quot; has an invalid value ({1})..
        /// </summary>
        internal static string Env_InvalidValueFmt {
            get {
                return ResourceManager.GetString("Env_InvalidValueFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment variable &quot;{0}&quot; has an invalid {1} value ({2})..
        /// </summary>
        internal static string Env_InvalidValueTypeFmt {
            get {
                return ResourceManager.GetString("Env_InvalidValueTypeFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While parsing &quot;{0}&quot;, value &quot;{1}&quot; has an unterminated multi-line value..
        /// </summary>
        internal static string Env_UnterminatedMultiLineValueFmt {
            get {
                return ResourceManager.GetString("Env_UnterminatedMultiLineValueFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP response appears to be malformed and could not be deserialized..
        /// </summary>
        internal static string Http_ResponseMalformed {
            get {
                return ResourceManager.GetString("Http_ResponseMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received HTTP response code {0} ({1})..
        /// </summary>
        internal static string Http_StatusCodeErrorFmt {
            get {
                return ResourceManager.GetString("Http_StatusCodeErrorFmt", resourceCulture);
            }
        }
    }
}
